services:
  mongo:
    container_name: "mongo-container"
    entrypoint: >
      /bin/bash -c '
        mkdir /data/keys | true &&
        openssl rand -base64 756 > /data/keys/keyfile.key &&
        chmod 400 /data/keys/keyfile.key &&
        chown mongodb:mongodb /data/keys/keyfile.key &&
        /usr/local/bin/docker-entrypoint.sh mongod --replSet rs0 --keyFile /data/keys/keyfile.key --bind_ip_all'
    image: "mongo:8.0"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - "mongo-data:/data"
    healthcheck:
      test: >
        mongosh
        -u $${MONGO_INITDB_ROOT_USERNAME}
        -p $${MONGO_INITDB_ROOT_PASSWORD}
        --eval "
          try {
            rs.status()
          } catch (err) {
            rs.initiate({ _id: 'rs0', members: [ { _id: 0, host: '127.0.0.1:27017' } ] })
          }
        " | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    restart: unless-stopped

volumes:
  mongo-data:
